### PR TITLE
Fixed syntax errors in battery i3-block

### PR DESCRIPTION
**Pull request by jayywolff**
I was greatly inspired by your dotfiles and post on reddit so I stole a few ideas for my i3 setup. One thing I found broken was this battery script so I fixed that and now just submitting the patch back upstream.

### CODE REVIEW

**Comment by ethragur** [comment]
Thank you for the fix :)

**Comment by jayywolff** [comment]
You're welcome sir. Also If you want to add some functionality,  In mine I've even taken a step further and added a few lines to indicate if the AC adapter is currently plugged in. 

```
charging=$(acpi -b | grep -c Discharging)
if [ ! $charging -eq 1 ]
then echo "  $perc%"
```

**Comment by ethragur** [comment]
I updated my battery script 2e389f560eca402846da038bd225ef5bd4dfc3f5

**Comment by ethragur** [comment]
I took it from the original script used with i3blocks, my bash scripting is really bad ;)

**Pull request merged**
